## 📚 Pandas Merging
> It is used to combine two DataFrames based on common keys using SQL-style join logic.<br>
> pd.merge()

In [1]:
import pandas as pd

In [2]:
personal=pd.read_csv(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Personal.csv")

In [4]:
professional=pd.read_csv(r"C:\Users\Prateek\Desktop\Repos\python-pandas-notes\sample_data\Professional.csv")

In [5]:
personal

     Name  Age     Contact    Address
0   Rahul   35  7865245701  Faridabad
1   Mohan   31  8384809385      Delhi
2  Subham   24  8475729435      Noida
3   Gagan   33  8990788505  Faridabad
4  Mayank   30  9316208108      Delhi
5   Komal   25  6917251118      Noida
6    Gita   28  7748351654  Faridabad
7  Babita   23  8709168475  Faridabad
8   Mukul   24  9137009386      Delhi

In [6]:
professional

      Name      Department  Salary  Experience (Year)
0    Rahul         Analyst   68582                  5
1    Gopal         Manager   73823                  5
2  Krishna         Analyst   79657                 10
3    Gagan      Programmer   79599                  8
4   Babita        Designer   56749                  3
5    Komal         Analyst   30472                  5
6   Munmun        Designer   94362                  2
7   Gungun         Analyst   95962                  1
8     Golu      Programmer   85310                  5
9    Rahul  Senior Analyst   98000                  7

In [7]:
# Now we have to join these two DataFrames based on the column Name

pd.merge(personal, professional, how="inner", left_on="Name", right_on="Name")

,Name,Age,Contact,Address,Department,Salary,Experience (Year)
0,Rahul,35,7865245701,Faridabad,Analyst,68582,5
1,Rahul,35,7865245701,Faridabad,Senior Analyst,98000,7
2,Gagan,33,8990788505,Faridabad,Programmer,79599,8
3,Komal,25,6917251118,Noida,Analyst,30472,5
4,Babita,23,8709168475,Faridabad,Designer,56749,3

In [9]:
# Left Join

pd.merge(personal, professional, how="left", left_on="Name", right_on="Name")

,Name,Age,Contact,Address,Department,Salary,Experience (Year)
0,Rahul,35,7865245701,Faridabad,Analyst,68582.0,5.0
1,Rahul,35,7865245701,Faridabad,Senior Analyst,98000.0,7.0
2,Mohan,31,8384809385,Delhi,NaN,NaN,NaN
3,Subham,24,8475729435,Noida,NaN,NaN,NaN
4,Gagan,33,8990788505,Faridabad,Programmer,79599.0,8.0
5,Mayank,30,9316208108,Delhi,NaN,NaN,NaN
6,Komal,25,6917251118,Noida,Analyst,30472.0,5.0
7,Gita,28,7748351654,Faridabad,NaN,NaN,NaN
8,Babita,23,8709168475,Faridabad,Designer,56749.0,3.0
9,Mukul,24,9137009386,Delhi,NaN,NaN,NaN

In [11]:
left_anti=pd.merge(personal, professional, how="left", left_on="Name", right_on="Name", indicator=True)

In [12]:
left_anti[left_anti["_merge"]=="left_only"]

,Name,Age,Contact,Address,Department,Salary,Experience (Year),_merge
2,Mohan,31,8384809385,Delhi,NaN,NaN,NaN,left_only
3,Subham,24,8475729435,Noida,NaN,NaN,NaN,left_only
5,Mayank,30,9316208108,Delhi,NaN,NaN,NaN,left_only
7,Gita,28,7748351654,Faridabad,NaN,NaN,NaN,left_only
9,Mukul,24,9137009386,Delhi,NaN,NaN,NaN,left_only

In [14]:
# Full outer join is also known as the universal join

pd.merge(personal, professional, how="outer", left_on="Name", right_on="Name", indicator=True)

,Name,Age,Contact,Address,Department,Salary,Experience (Year),_merge
0,Babita,23.0,8.709168e+09,Faridabad,Designer,56749.0,3.0,both
1,Gagan,33.0,8.990789e+09,Faridabad,Programmer,79599.0,8.0,both
2,Gita,28.0,7.748352e+09,Faridabad,NaN,NaN,NaN,left_only
3,Golu,NaN,NaN,NaN,Programmer,85310.0,5.0,right_only
4,Gopal,NaN,NaN,NaN,Manager,73823.0,5.0,right_only
5,Gungun,NaN,NaN,NaN,Analyst,95962.0,1.0,right_only
6,Komal,25.0,6.917251e+09,Noida,Analyst,30472.0,5.0,both
7,Krishna,NaN,NaN,NaN,Analyst,79657.0,10.0,right_only
8,Mayank,30.0,9.316208e+09,Delhi,NaN,NaN,NaN,left_only
9,Mohan,31.0,8.384809e+09,Delhi,NaN,NaN,NaN,left_only
10,Mukul,24.0,9.137009e+09,Delhi,NaN,NaN,NaN,left_only
11,Munmun,NaN,NaN,NaN,Designer,94362.0,2.0,right_only
12,Rahul,35.0,7.865246e+09,Faridabad,Analyst,68582.0,5.0,both
13,Rahul,35.0,7.865246e+09,Faridabad,Senior Analyst,98000.0,7.0,both
14,Subham,24.0,8.475729e+09,Noida,NaN,NaN,NaN,left_only

In [15]:
# from full outer join we can fetch all the other joins

### 📚 Some more Data Transformation methods.

In [16]:
df = pd.DataFrame(
[[0, 1], [2, 3]], index=["cat", "dog"], columns=["weight", "height"]
)

In [17]:
df

     weight  height
cat       0       1
dog       2       3

In [19]:
# above mentioned is in pivot table format to reverse it we can use stack() method.

In [24]:
x=df.stack().reset_index()

In [27]:
x.columns=["Category", "Attributes", "Values"]

In [28]:
x

  Category Attributes  Values
0      cat     weight       0
1      cat     height       1
2      dog     weight       2
3      dog     height       3